# Generated by Django 4.0.4 on 2022-05-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='Tema', max_length=50, null=True, verbose_name='Taqyryp'),
        ),
    ]
